# Generated by Django 4.2.13 on 2024-12-07 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_rename_replies_reply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['-date_added']},
        ),
        migrations.AddField(
            model_name='reply',
            name='parent_comment',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.comment'),
            preserve_default=False,
        ),
    ]
