# Generated by Django 4.2.13 on 2024-12-07 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_reply_options_reply_parent_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='parent_comment',
            field=models.ForeignKey(default='Reply Comment', on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.comment'),
        ),
    ]
