# Generated by Django 4.2.13 on 2024-12-07 12:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_reply_parent_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='id',
            field=models.CharField(default=uuid.UUID('e3a74fad-a05b-4f0c-adc6-6770e6f3dcac'), editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
