# Generated by Django 4.2.13 on 2024-12-08 03:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_reply_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='id',
            field=models.CharField(default=uuid.UUID('b7b542ea-127c-4e7c-b1cc-e6d69a699bc4'), editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
