# Generated by Django 4.2.13 on 2024-12-08 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_reply_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='id',
            field=models.CharField(editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
