# Generated by Django 4.2.13 on 2024-12-10 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_remove_reply_parent_comment_reply_comment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
